services:
  marzban:
    image: ${MARZBAN_DOCKER_IMAGE:-ghcr.io/unblocked-monkeys/marzban:latest}
    restart: always
    env_file: .env
    network_mode: host
    volumes:
      - /var/lib/marzban:/var/lib/marzban
